### ISSUE TITLE
Unable to find OHS configuration

### ISSUE THREAD

**Issue by karunakarchil** [justinpaulthekkan/oracle-fmw-tooling#2]
Successfully created domain not able to  find OHS information.

/u01/app/oracle/wcchomeNW/oracle_common/common/bin/wlst.sh create_domain_off.py -h /u01/app/oracle/wcchome/user_projects/domains/TEST_domain -c localhost:1521:orcl -m TEST --domain_name TEST_domain --db_password welcome1 --nm_password Welcome1 --as_password Welcome1 wls ucm wccadf ohs

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating the Domain.
Loading Required Templates.
        Basic WebLogic Server Domain version 12.2.1
        Oracle Enterprise Manager version 12.2.1
        Oracle Universal Content Management - Content Server version 12.2.1
        Oracle WebCenter Content - Web UI version 12.2.1
        Oracle HTTP Server (Collocated) version 12.2.1
Setting Domain Options.
Configuring Admin Server.
        SSL
        ServerStart
Configuring Admin User.
Configuring Security Configuration.
Configuring Nodemanager.
Configuring feature em.
        Updating Data Source LocalSvcTblDataSource
Configuring feature ucm.
        Updating Filestore CsJMSFileStore
        Creating cluster ucm_cluster1
        Targeting resources to cluster ucm_cluster1
Configuring feature wccadf.
        Updating Key wccadfConnectUser in Credential oracle.wcc.security
        Updating Data Source mds-WCCUIMDSREPO
        Creating cluster wccadf_cluster1
        Targeting resources to cluster wccadf_cluster1
Configuring feature ohs.
Data Sources Auto Config
Writing Domain Configuration.
Writing boot.properties.
Domain built successfully.

**Comment by freneticdisc** [comment]
I have not written the code to update the OHS configuration and this remains a manual activity at this time after the admin server has been started.
