### ISSUE TITLE
 WebLogic Domains cluster creating with Oracle Fusion Middleware 12c components using scripts.

### ISSUE THREAD

**Issue by karunakarchil** [justinpaulthekkan/oracle-fmw-tooling#3]
Hi
Any possibility to create cluster domain with Oracle Fusion Middleware 12c components using scripts.

**Comment by freneticdisc** [comment]
Yes. You can use the add_servers_onl.py script to add managed servers to the cluster. You can refer to my blog here: https://blogs.oracle.com/OracleWebCenterSuite/entry/docker_compose_fusion_middleware_12c. Use the content server entry and duplicate it with different container name and it will create a 2 node cluster.
