### ISSUE TITLE
Oracle Web Services Manager can we enable while creating domain

### ISSUE THREAD

**Issue by karunakarchil** [justinpaulthekkan/oracle-fmw-tooling#4]
Hi,

Can we enable while creating domain Oracle Web Services Manager?  ' [wls] [bpm|soa] [ibr] [ucm] [capture] [wccadf] [portal] [pagelet portlet] [discussions] [analytics] [sites] [vs] [insights] [sc] [ss] [ohs]' 
Which option i need to select?

wlst.[sh|cmd] build_domain_off.py [-?] -h domain_home [-s shared_home] -c db_connect_string -m db_prefix [-w password_file] [--domain_name domain_name] [--nm_port nm_port] [--as_port adminserver_port] [--as_ssl_port adminserver_sslport] [--db_password db_datasource_passwd] [--nm_password nodemanager_passwd] [--as_password adminserver_password] [wls] [bpm|soa] [ibr] [ucm] [capture] [wccadf] [portal] [pagelet portlet] [discussions] [analytics] [sites] [vs] [insights] [sc] [ss] [ohs]`

**Comment by karunakarchil** [comment]
Creating a UCM Domain With OWSM Enabled (Doc ID 1332250.1)

**Comment by freneticdisc** [comment]
You can but I have not coded that part. You will have to update the JSON files with the domain extension jar and other parameters. Then use the key used in the JSON while executing the script.

**Comment by karunakarchil** [comment]
Can you help on below entry, i need to add anything addtional?
"ows": {
        "version": "12.2.1.0",
        "template-name": "Oracle WSM Policy Manager"
    }
