### ISSUE TITLE
Issue in creating Weblogic Domain 12.2.1.2

### ISSUE THREAD

**Issue by TarakChadaram** [justinpaulthekkan/oracle-fmw-tooling#6]
Hello All,

I am trying to create a domain using WLST command in a python script .However I am not able to figure it out the errors.Also I am not sure how to capture output of the script into a file.Tried redirect() command but no luck it just creating an empty file.
Please help with pointers

*********py script**************

OSB_REPOS_DBURL = 'jdbc:oracle:thin:@//hostname:3201/dnhsoa01'
OSB_REPOS_DB_PASSWORD = '************'
OSB_REPOS_DBUSER_PREFIX = 'Hostname'

#Admin Server Configuration properties
ADMIN_SERVER_HOST = 'HOSTNAME'
ADMIN_SERVER_PORT = 7001

#SOA Server Configuration properties
OSB_SERVER_HOST = 'HOSTNAME'
OSB_SERVER_PORT = 7003

#Folder Locations
MW_HOME = '/oraapp/product/fmw'
DOMAIN_HOME = '/oraapp/config/domains/custsvc_osb'

def changeDatasourceToXA(datasource):
  print '>>>>>>> Change datasource '+datasource
  cd('/')
  cd('/JDBCSystemResource/'+datasource+'/JdbcResource/'+datasource+'/JDBCDriverParams/NO_NAME_0')
  set('DriverName','oracle.jdbc.xa.client.OracleXADataSource')
  set('UseXADataSourceInterface','True')
  cd('/JDBCSystemResource/'+datasource+'/JdbcResource/'+datasource+'/JDBCDataSourceParams/NO_NAME_0')
  set('GlobalTransactionsProtocol','TwoPhaseCommit')
  cd('/')

def alterDatasource(datasource_name, schema_sufix, driver_name):
        cd('/JDBCSystemResource/' + datasource_name + '/JdbcResource/' + datasource_name + '/JDBCDriverParams/NO_NAME_0')
        set('URL',OSB_REPOS_DBURL)
        set('PasswordEncrypted',OSB_REPOS_DB_PASSWORD)
        if driver_name:
                set('DriverName', driver_name)
        cd('Properties/NO_NAME_0/Property/user')
        set('Value',OSB_REPOS_DBUSER_PREFIX+'_'+schema_sufix)

redirect('/home/s-fmwadmin/InstallationScripts/wlst.log', 'false')
#=======================================================================================
# Open a domain template.
#=======================================================================================

readTemplate(MW_HOME+'/wlserver/common/templates/wls/wls.jar')

#=======================================================================================
# Configure the Administration Server and SSL port.
#
# To enable access by both local and remote processes, you should not set the
# listen address for the server instance (that is, it should be left blank or not set).

cd('Servers/AdminServer')
set('ListenAddress', ADMIN_SERVER_HOST)
set('ListenPort', ADMIN_SERVER_PORT)

#=======================================================================================
# Define the user password for weblogic.
#=======================================================================================

cd('/')
cd('Security/base_domain/User/weblogic')
cmo.setPassword('welcome1')

#=======================================================================================
# Write the domain and close the domain template.
#=======================================================================================

setOption('OverwriteDomain', 'true')

#Creating default coherence cluster
create('defaultCoherenceCluster', 'CoherenceClusterSystemResource')

cd('/')
create('osb_server1','Server')
cd('Server/osb_server1')
set('ListenPort', OSB_SERVER_PORT)
set('ListenAddress', OSB_SERVER_HOST)
set('CoherenceClusterSystemResource', 'defaultCoherenceCluster')

#assigning target for default coherence cluster
cd('/')
assign('Server','osb_server1','CoherenceClusterSystemResource','defaultCoherenceCluster')

cd('/CoherenceClusterSystemResource/defaultCoherenceCluster')
set('Target', 'osb_server1')

print ">>>>>>> Creating WLS Domain"

writeDomain(DOMAIN_HOME)

closeTemplate()

#=======================================================================================
# Exit WLST.
#=======================================================================================

print ">>>>>>> Extending the domain for OSB"
readDomain(DOMAIN_HOME)

print ">>>>>>> Adding Webservice Template"
addTemplate(MW_HOME+'/oracle_common/common/templates/wls/oracle.wls-webservice-template.jar')

print ">>>>>>> Adding OSB Template"
addTemplate(MW_HOME+'/osb/common/templates/wls/oracle.osb_template.jar')

print ">>>>>>> Adding Insight Template"
addTemplate(MW_HOME+'/osb/common/templates/wls/oracle.osb.procmon_template.jar')
print '>>>>>>> Datasources Change Start'
print '>>>>>>> Change datasource LocalScvTblDataSource'

cd('/JDBCSystemResource/LocalSvcTblDataSource/JdbcResource/LocalSvcTblDataSource/JDBCDriverParams/NO_NAME_0')
set('URL',OSB_REPOS_DBURL)
cmo.setPasswordEncrypted(OSB_REPOS_DB_PASSWORD)
cd('Properties/NO_NAME_0/Property/user')
set('Value',OSB_REPOS_DBUSER_PREFIX+'_STB')

print '>>>>>>> Call getDatabaseDefaults to read details from service table'
getDatabaseDefaults()

#changeDatasourceToXA('EDNDataSource')
changeDatasourceToXA('OraSDPMDataSource')
changeDatasourceToXA('SOADataSource')

print '>>>>>>> Datasources Change End'

print '>>>>>>> Add server groups to AdminServer'
serverGroup = ["WSM-CACHE-SVR" , "WSMPM-MAN-SVR" , "JRF-MAN-SVR"]
setServerGroups('AdminServer', serverGroup)

print '>>>>>>> Add server group(s) to osb_server1'
serverGroup = ["OSB-MGD-SVRS-COMBINED"]
setServerGroups('osb_server1', serverGroup)

print '>>>>>> Alter Datasource name'
alterDatasource('opss-audit-DBDS', 'IAU_APPEND', None)
alterDatasource('opss-audit-viewDS', 'IAU_VIEWER', None)
alterDatasource('opss-data-source', 'OPSS', None)
alterDatasource('LocalSvcTblDataSource', 'STB', None)
alterDatasource('wlsbjmsrpDataSource', 'SOAINFRA', None)
alterDatasource('OraSDPMDataSource', 'UMS', None)

alterDatasource('BamDataSource', 'SOAINFRA', None)
alterDatasource('mds-bam', 'MDS', None)
#alterDatasource('BamJobSchedDataSource', 'WLS', None)
alterDatasource('OraSDPMDataSource', 'UMS', None)

print '>>>>>>> Update Domain....... Please wait.. takes little time to populate OPSS Schema'
updateDomain()

print '>>>>>>> Update Domain Completed'

closeDomain()

print '>>>>>>> Domain Creation Completed'

exit()

====Error
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/home/s-fmwadmin/InstallationScripts/OSBDomain_12c.py", line 165, in ?
  File "/tmp/WLSTOfflineIni4459921607751339716.py", line 135, in updateDomain
  File "/tmp/WLSTOfflineIni4459921607751339716.py", line 19, in command
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: custsvc_osb
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//gaxgpor52vd:3201/dnhsoa01
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//gaxgpor52vd:3201/dnhsoa01
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties:
user:GAXGPOA165VD_IAU_APPEND
username:GAXGPOA165VD_IAU_APPENDJDBC Properties:
user:GAXGPOA165VD_OPSS
username:GAXGPOA165VD_OPSS
64254: Check log for more detail.

        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2768)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:701)
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error updating domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: custsvc_osb
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//gaxgpor52vd:3201/dnhsoa01
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//gaxgpor52vd:3201/dnhsoa01
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties:
user:GAXGPOA165VD_IAU_APPEND
username:GAXGPOA165VD_IAU_APPENDJDBC Properties:
user:GAXGPOA165VD_OPSS
username:GAXGPOA165VD_OPSS
64254: Check log for more detail.

**Comment by kishoremanchik** [comment]
Do we have the solution for this issue? 

Facing similar issue :

java.lang.IllegalStateException: SecurityContext:
 Domain Name: wcp_domain
 JDBC URL: opss-audit-DBDS:
 JDBC URL: opss-data-source:
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties: 
user:FMW_IAU_APPEND
username:FMW_IAU_APPENDJDBC Properties: 
user:FMW_OPSS
username:FMW_OPSS
	at com.oracle.cie.domain.progress.template.importer.ImporterOPSSProcessingPhase.initialize(ImporterOPSSProcessingPhase.java:40)
	at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.processOPSS(OPSSProcessingPhase.java:154)
	at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.execute(OPSSProcessingPhase.java:54)
	at com.oracle.cie.domain.progress.AbstractProgressGenerator.run(AbstractProgressGenerator.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.oracle.cie.domain.security.external.ConfigSecurityException: oracle.security.opss.tools.lifecycle.LifecycleException: 
JPS-01047: Cannot persist the wallet. Reason java.io.IOException: No locks available.
	at oracle.security.opss.tools.lifecycle.cie.OpssSecurityConfiguration.initializeSubsystem(OpssSecurityConfiguration.java:191)
	at com.oracle.cie.domain.progress.template.importer.ImporterOPSSProcessingPhase.initialize(ImporterOPSSProcessingPhase.java:36)
	... 4 more
