### ISSUE TITLE
Issue with the launching of the wlst script when creating domain

### ISSUE THREAD

**Issue by wtran168** [justinpaulthekkan/oracle-fmw-tooling#7]
I'm having an issue with using the create_domain script

```
[oratest@ip oracle-fmw-tooling-master]$ /u02/app/oratest/weblogic/oracle_common/common/bin/wlst.sh create_domain_off.py -h /u02/app/oratest/domains -c ip:1521/dev -m TST --domain_name dev_domain --nm_port 5556 --as_port 7001 --as_ssl_port 7005 --db_password Oracle123 -nm_password Oracle123 --as_password Oracle123
 wls ibr ucm wccadf

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Problem invoking WLST - Traceback (innermost last):
  File "/u02/auto/dev/oracle-fmw-tooling-master/create_domain_off.py", line 232, in ?
  File "/u02/app/oratest/weblogic/wlserver/common/wlst/modules/jython-modules.jar/Lib/getopt$py.class", line 74, in getopt
  File "/u02/app/oratest/weblogic/wlserver/common/wlst/modules/jython-modules.jar/Lib/getopt$py.class", line 124, in do_shorts
  File "/u02/app/oratest/weblogic/wlserver/common/wlst/modules/jython-modules.jar/Lib/getopt$py.class", line 139, in short_has_arg
GetoptError: option -n not recognized
```
It's using the Jython libraries v 2.2 included with weblogic.

I have python2.7 installed, and it works for the installation and repository creation.

I have also found a possible solution to embed Jython 2.7:
https://technology.amis.nl/2015/10/04/how-to-use-wlst-as-a-jython-2-7-module/

Please help in getting it working.

**Comment by freneticdisc** [comment]
I don't think this issue is related to Jython version. The error message clearly points to an option used: "-n". Looking at the command you have used, please change "-nm_password Oracle123" to "--nm_password Oracle123" and you should be good.

**Comment by wtran168** [comment]
Thanks. That was the problem. It is now working. I am using 12.2.1.2.0 software versions without issues.
